name: flutter_dsfr
description: Flutter implementation of the french government design system.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_dsfr

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  alchemist: ^0.4.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Marianne
      fonts:
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-Thin.otf
          weight: 100
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-ThinItalic.otf
          weight: 100
          style: italic
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-Light.otf
          weight: 300
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-LightItalic.otf
          weight: 300
          style: italic
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-Regular.otf
          weight: 400
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-RegularItalic.otf
          weight: 400
          style: italic
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-Medium.otf
          weight: 500
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-MediumItalic.otf
          weight: 500
          style: italic
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-Bold.otf
          weight: 700
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-BoldItalic.otf
          weight: 700
          style: italic
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-ExtraBold.otf
          weight: 800
        - asset: packages/flutter_dsfr/fonts/Marianne/Marianne-ExtraBoldItalic.otf
          weight: 800
          style: italic
    - family: Spectral
      fonts:
        - asset: packages/flutter_dsfr/fonts/Spectral/Spectral-Light.ttf
          weight: 300
        - asset: packages/flutter_dsfr/fonts/Spectral/Spectral-LightItalic.ttf
          weight: 300
          style: italic
        - asset: packages/flutter_dsfr/fonts/Spectral/Spectral-Regular.ttf
          weight: 400
        - asset: packages/flutter_dsfr/fonts/Spectral/Spectral-Italic.ttf
          weight: 400
          style: italic
    - family: Remix Icon
      fonts:
        - asset: packages/flutter_dsfr/icons/remixicon.ttf
