name: Build example

on:
  workflow_run:
    workflows: [Test workflow]
    branches: main
    types: [completed]

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
          channel: "stable"
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: example
          webRenderer: canvaskit
          baseHref: /flutter_dsfr_example/
