name: Build example

on:
    workflow_run:
        workflows: Test workflow
        branches: main
        types: completed
        
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build example
    runs-on: ubuntu-latest
    defaults:
        run:
           working-directory: example 
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.5.3
      - name: Fetch dependencies
        run: flutter pub get
      - name: Build example project to ensure compatibility
        run: flutter build web --release
